# Generated by Django 5.2.4 on 2025-12-02 13:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profil_foto/6b9f250c.png', null=True, upload_to=users.models.rename_image),
        ),
    ]
