# Generated by Django 5.2.4 on 2025-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_weight_lower', models.IntegerField()),
                ('unit_weight_upper', models.IntegerField()),
                ('angle_of_repose', models.IntegerField()),
                ('internal_friction_mean', models.IntegerField()),
                ('internal_friction_factor', models.IntegerField()),
                ('lateral_pressure_mean', models.IntegerField()),
                ('lateral_pressure_factor', models.IntegerField()),
                ('wall_friction_d1', models.IntegerField()),
                ('wall_friction_d2', models.IntegerField()),
                ('wall_friction_d3', models.IntegerField()),
                ('wall_friction_factor', models.IntegerField()),
                ('patch_load_factor', models.IntegerField()),
            ],
        ),
    ]
