# Generated by Django 5.2.4 on 2025-09-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
